name: "CI"
on:
  pull_request:
  push:
jobs:
  tests-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18
      with:
        extra_nix_config: "system-features = nixos-test benchmark big-parallel kvm"
    - run: nix build
    - run: nix fmt . -- --check
    - run: nix flake check
  tests-darwin:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18
      with:
        extra_nix_config: "system-features = nixos-test benchmark big-parallel kvm"
    - run: nix build
    - run: nix fmt . -- --check
    - run: nix flake check
